apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: frontend-claim0
  name: frontend-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
