apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - name: "12345"
    port: 12345
    targetPort: 12345
  selector:
    app: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
