# biz_server.toml

ver = "0.0.1"
#logPath = "/tmp/frontend.log"
serverId = 1

[server.server]
name = "session"
protoName = "brpc"
addr = "0.0.0.0:10000"

[server.discovery]
serviceName = "session"
nodeID = "node1"
rPCAddr = "session:10000"
etcdAddrs = ["http://etcd:2379"]
interval = "2s"
tTL = "10s"

[authSessionRpcClient]
serviceName = "auth_session"
etcdAddrs = ["http://etcd:2379"]
balancer = "round_robin"

[bizRpcClient]
serviceName = "biz_server"
etcdAddrs = ["http://etcd:2379"]
balancer = "round_robin"

[nbfsRpcClient]
serviceName = "upload"
etcdAddrs = ["http://etcd:2379"]
balancer = "round_robin"

[syncRpcClient]
serviceName = "sync2"
etcdAddrs = ["http://etcd:2379"]
balancer = "round_robin"

[[redis]]
name = "cache"
addr = "redis:6379"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
dbNum = "0"
password = ""
