apiVersion: v1
kind: Service
metadata:
  labels:
    app: biz-server
  name: biz-server
spec:
  ports:
  - name: "10001"
    port: 10001
    targetPort: 10001
  selector:
    app: biz-server
status:
  loadBalancer: {}
