# auth_session.toml

ver = "0.0.1"
#logPath = "/tmp/biz_server.log"

[rpcServer]
addr = "0.0.0.0:10010"

[rpcServer.rpcDiscovery]
serviceName = "auth_session"
nodeID = "node1"
rPCAddr = "auth-session:10010"
etcdAddrs = ["http://etcd:2379"]
interval = "2s"
tTL = "10s"

[cache]
adapterName = "redis"
config = "{\"conn\":\"redis:6379\",\"dbNum\":\"0\"}"

[[mysql]]
name = "immaster"
dsn = "phuongct:12345@tcp(mysql:3306)/chatengine?charset=utf8mb4"
active = 5
idle = 2

[[mysql]]
name = "imslave"
dsn = "phuongct:12345@tcp(mysql:3306)/chatengine?charset=utf8mb4"
active = 5
idle = 2
