version: "3"

services:
  etcd:
    image: appcelerator/etcd:3.3.3
    restart: always
    logging:
      options:
        max-size: "50M"
        max-file: "5"
    volumes:
      - /home/phuong/Documents/chatengine/docker/etcd/data:/data
    ports: 
      - 2379:2379
  mysql:
    image: mysql:5.7.17
    restart: always
    logging:
      options:
        max-size: "50M"
        max-file: "5"
    volumes:
      - /home/phuong/Documents/chatengine/docker/mysql/mysql.cnf:/etc/mysql/conf.d
      - /home/phuong/Documents/chatengine/docker/mysql/init-sql:/docker-entrypoint-initdb.d
      - /home/phuong/Documents/chatengine/docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=chatengine
      - MYSQL_DATABASE=chatengine
    ports:
      - 3306:3306
  redis:
    image: redis:5.0.0-alpine3.8
    restart: always
    logging:
      options:
        max-size: "50M"
        max-file: "5"
    volumes:
      - /home/phuong/Documents/chatengine/docker/redis/redis.conf:/etc/redis/redis.conf
      - /home/phuong/Documents/chatengine/docker/redis/data:/data
    entrypoint: redis-server /etc/redis/redis.conf
    ports: 
      - 6379:6379
  chatengine:
    image: phuongct/chatengine:latest
    restart: always
    logging:
      options:
        max-size: "50M"
        max-file: "5"
    environment:
      - TZ=Asia/Shanghai
      # IMPORTANT: replace to your own host IP.
      - CHATENGINE_HOST=127.0.0.1
      # options to reset etcd,redis,mysql
      # - ETCD_URL=http://etcd:2379
      # - REDIS_HOST=redis:6379
      # - MYSQL_URI=root:chatengine@tcp(mysql:3306)/chatengine?charset=utf8mb4
    volumes:
      - /home/phuong/Documents/chatengine/docker/nbfs:/opt/nbfs
    ports:
      - 12345:12345
    depends_on:
      - mysql
      - etcd
      - redis
  auth-key:
    image: phuongct/auth-key:latest
    restart: always
    logging: 
      options: 
        max-size: "50M"
        max-file: "5"
    environment: 
      - TZ:Asia/Ho_Chi_Minh
      - CHATENGINE_HOST=127.0.0.1
    volumes:
      - /home/phuong/Documents/chatengine/docker/nbfs:/opt/nbfs
    ports:
      - 12345:12345
    depends_on:
      - mysql
      - etcd
      - redis
  auth-session:
    image: phuongct/auth-session
    restart: always
    logging: 
      options:
        max-size: "50M"
        max-file: "5"
    environment: 
      - TZ:Asia/Ho_Chi_Minh
    volumes: /home/phuong/Documents/chatengine/docker/nbfs:/opt/nbfs
    ports: 
      - 12345;12345
    depends_on:
      - mysql
      - etcd
      - redis 
