apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis-claim1
  name: redis-claim1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
