apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-claim2
  name: mysql-claim2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
