apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: session
  name: session
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session
  template:
    metadata:
      labels:
        app: session
    spec:
      containers:
      - env:
        - name: CHATENGINE_HOST
          value: session
        image: phuongct/session:latest
        name: session
        ports:
        - containerPort: 10000
        resources: {}
        volumeMounts:
        - mountPath: /opt/nbfs
          name: session-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: session-claim0
        persistentVolumeClaim:
          claimName: session-claim0
status: {}
