apiVersion: v1
kind: Service
metadata:
  labels:
    app: session
  name: session
spec:
  ports:
  - name: "10000"
    port: 10000
    targetPort: 10000
  selector:
    app: session
status:
  loadBalancer: {}
