# auth_key.toml

ver = "0.0.1"
serverId = 1
keyFile = "server_pkcs1.key"
KeyFingerprint = "12240908862933197005"

[server.server]
name = "handshake"
protoName = "brpc"
addr = "0.0.0.0:10005"

[authSessionRpcClient]
serviceName = "auth_session"
etcdAddrs = ["http://etcd:2379"]
balancer = "round_robin"

[server.discovery]
serviceName = "handshake"
nodeID = "node1"
rPCAddr = "auth-key:10005"
etcdAddrs = ["http://etcd:2379"]
interval = "2s"
tTL = "10s"
