apiVersion: v1
kind: Service
metadata:
  labels:
    app: sync
  name: sync
spec:
  ports:
  - name: "10002"
    port: 10002
    targetPort: 10002
  selector:
    app: sync
status:
  loadBalancer: {}
