apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-key
  name: auth-key
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-key
  template:
    metadata:
      labels:
        app: auth-key
    spec:
      containers:
      - env:
        - name: CHATENGINE_HOST
          value: auth-key
        image: phuongct/auth-key:latest
        name: auth-key
        ports:
        - containerPort: 10005
        resources: {}
        volumeMounts:
        - mountPath: /opt/nbfs
          name: auth-key-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: auth-key-claim0
        persistentVolumeClaim:
          claimName: auth-key-claim0
status: {}
