apiVersion: v1
kind: Service
metadata:
  labels:
    app: document
  name: document
spec:
  ports:
  - name: "10009"
    port: 10009
    targetPort: 10009
  selector:
    app: document
status:
  loadBalancer: {}
